<a href="https://colab.research.google.com/github/singhshahrahul/AI-ML/blob/main/04_intro_of_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IN this notebook we are going to cover some of the most fundamental concepts of tensor using TensorFlow

we are going to cover:
* Introduction to tensor
* Getting information from tensor
* Manipulating tensor
* Using @tf.function (a way to speed up your regular Python funtion)
* using GPUs with TensorFlow (or TPU)


# Intro to Tensor

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.20.0


In [ ]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the dimensions
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
mat = tf.constant([[10,4],
                  [4,10]])
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [ 4, 10]], dtype=int32)>

In [ ]:
mat.ndim

2

In [ ]:
#another matrix
another_mat = tf.constant([[4,5],
                           [6,7],
                           [2,6]], dtype=tf.float16) #Specify the datatype with dtype parameter
another_mat

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[4., 5.],
       [6., 7.],
       [2., 6.]], dtype=float16)>

In [ ]:
another_mat.ndim

2

In [ ]:
#create a tensor
tensor = tf.constant([[[1,3,5],
                       [3,6,8]],
                      [[2,4,6],
                       [6,8,3]],
                      [[1,9,4],
                       [2,8,4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 3, 5],
        [3, 6, 8]],

       [[2, 4, 6],
        [6, 8, 3]],

       [[1, 9, 4],
        [2, 8, 4]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Creating tensor with `tf.Variable`

In [ ]:
#Changable and unchangable
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's change one of the element in our changable tensor
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

We can create random tensor by using `tf.random.Generator` class

In [ ]:
#create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2)) #create tensor from a normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2)) #create tensor from a normal distribution

In [ ]:
#are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#Shuffle the order of element in tensor

In [ ]:
not_shuffled = tf.constant([[4,9],
                            [2,3],
                            [7,1]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 1],
       [2, 3],
       [4, 9]], dtype=int32)>

 If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.random.shuffle(seed=42) sets the operation seed.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

In [ ]:
tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled, seed=(42)) #Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 9],
       [2, 3],
       [7, 1]], dtype=int32)>

#Other ways to make tensor

In [ ]:
#Tensor of all ones
tf.ones([7,4])

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([7,4])

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

**turn Numpy arrays into Tensor**

tensors can run on GPU much faster

In [ ]:
import numpy as np
np_A = np.arange(1,25, dtype=np.int32)
np_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
#Convert to tensor
A = tf.constant(np_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(np_A, shape=(3,4,2))
A

<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

#Getting information from tensor

* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
#Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Get various attributes of our tensor
print("Data type of every element:", rank_4_tensor.dtype)
print("Number of dimension:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Element along the 0 axis:", rank_4_tensor.shape[0])
print("Element along the last axis:", rank_4_tensor.shape[-1])
print("Total no. of elements:", tf.size(rank_4_tensor))
print("Total no. of elements:", tf.size(rank_4_tensor).numpy())

Data type of every element: <dtype: 'float32'>
Number of dimension: 4
Shape of tensor: (2, 3, 4, 5)
Element along the 0 axis: 2
Element along the last axis: 5
Total no. of elements: tf.Tensor(120, shape=(), dtype=int32)
Total no. of elements: 120


#Indexing tensor

Tensor cna be indexed just like Python list.


In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element form each dimension form each index exvept for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Rank 2 tensor
rank_2_tensor = tf.constant([[3,7],
                             [4,9]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#Get the last item of each of our rank 2 tensor
rank_2_tensor[:, 1:] #or [:, -1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[7],
       [9]], dtype=int32)>

In [ ]:
#Add extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [7]],

       [[4],
        [9]]], dtype=int32)>

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #-1 means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [7]],

       [[4],
        [9]]], dtype=int32)>

In [ ]:
#Expand the 0 axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 7],
        [4, 9]]], dtype=int32)>

#Manipulating tensors (tensor operations)

basic operation - `+`, `-`, `*`, `/`

In [ ]:
tensor = tf.constant([[10,7],
                      [3,9]])
tensor + 10 #However original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 19]], dtype=int32)>

In [ ]:
#We van use the tensorflow built in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  90]], dtype=int32)>

#Matrix multiplication

In [ ]:
#Matrix multiplication with tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 133],
       [ 57, 102]], dtype=int32)>

In [ ]:
#With python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 133],
       [ 57, 102]], dtype=int32)>

In [ ]:
#create a (3,2) tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
#another
Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
#We have to change the shape of Y (or X)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#Can do same with transpose
X, tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(X, (2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

in matrix multiplication always use transpose.

#Change data type of tensors

In [ ]:
#Tensor with default datatype
B = tf.constant([4.2, 5.1])
C = tf.constant([4, 5])

B.dtype, C.dtype

(tf.float32, tf.int32)

In [ ]:
#change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([4.2, 5.1], dtype=float16)>,
 tf.float16)

In [ ]:
E = tf.cast(C, dtype=tf.float32)
E.dtype

tf.float32

In [ ]:
E_16 = tf.cast(E, dtype=tf.float16)
E_16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([4., 5.], dtype=float16)>

#Aggregating tensor

condensing them  from multiple values down to a smaller amount of values

In [ ]:
#Get the absolute value
x = tf.constant([-7, 10])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

**let's go through the following forms of aggrigation**

* get minimum
* get maximum
* get the mean of a tensor
* get the sum of a tensor

In [ ]:
# create a random tensor of value between 0 to 100 of size 50
r = tf.constant(np.random.randint(0, 100, size=50))
r

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([14, 60, 90, 18, 91, 36, 36, 50, 75, 95, 75, 44, 50, 36, 95, 71, 14,
       39, 33,  5, 75, 14, 21, 74, 20, 64, 83,  9,  6, 59, 24, 55, 94, 94,
       74, 48, 74, 87, 36, 55, 64, 34, 58, 53, 84, 59, 71, 20, 74,  9])>

In [ ]:
tf.size(r), r.shape, r.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#find the minimun
tf.reduce_min(r)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [ ]:
#find the maximum
tf.reduce_max(r)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [ ]:
#Mean
tf.reduce_mean(r)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [ ]:
#Sum
tf.reduce_sum(r)

<tf.Tensor: shape=(), dtype=int64, numpy=2619>

In [ ]:
#to find the variance of our tensor we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(r)

<tf.Tensor: shape=(), dtype=int64, numpy=748>

In [ ]:
tf.math.reduce_variance(tf.cast(r, dtype=tf.float32))  #we have to change datatype to float32

<tf.Tensor: shape=(), dtype=float32, numpy=748.275634765625>

In [ ]:
tf.math.reduce_std(tf.cast(r, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.35462760925293>

#Find the positional maximum and minimum

In [ ]:
#New tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#find teh positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
#check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

#Squeezing a tensor(removing all single dimensions)

In [ ]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
#Remove single dimensions
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))

#One-hot-encoding

In [ ]:
#create a list of indices
some_list = [0,1,2,3]

#One hot encode our list fo indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify custom value for one hot
tf.one_hot(some_list, depth=4, on_value="hey", off_value="there")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hey', b'there', b'there', b'there'],
       [b'there', b'hey', b'there', b'there'],
       [b'there', b'there', b'hey', b'there'],
       [b'there', b'there', b'there', b'hey']], dtype=object)>

Squaring, log, Square root

In [ ]:
t = tf.range(1, 10)
t

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square
tf.square(t)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Square root
tf.sqrt(tf.cast(t, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Log
tf.math.log(tf.cast(t, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#Tensor and Numpy

In [ ]:
#create a tensor directly from numpy array
J = tf.constant(np.array([1., 4., 5.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 4., 5.])>

In [ ]:
#convert tensor to numpy
np.array(J), type(np.array(J))

(array([1., 4., 5.]), numpy.ndarray)

In [ ]:
#another method
J.numpy(), type(J.numpy())

(array([1., 4., 5.]), numpy.ndarray)

In [ ]:
#difference between tensor from numpy and list(tensorflow)
numpy_J = tf.constant(np.array([4., 5., 7.]))
tensor_J = tf.constant([4., 5., 7.])

#check datatype
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)